export const promptList: string[] = [
    'Les chaussettes se rebellent !',
    'Le retour des biscuits sablés',
    'Les lapins ont pris le contrôle !',
    'Encore un coup des moustaches de chat',
    'Les pandas envahissent les jardins',
    'Les licornes se sont échappées',
    'Les tomates chantent sous la pluie',
    'Le mystère des chaussons perdus',
    'Les peluches ont des secrets',
    'Les bonbons à la rescousse',
    'Les biscuits de Noël attaquent',
    'Les moutons rêvent de voyages',
    'Les crayons ont disparu !',
    'Les ours en peluche font grève',
    'Les plantes dansent la samba',
    'Les poissons rouges sont des espions',
    'Les biscuits roulés dominent le monde',
    'Les araignées ont des projets',
    'Les manchots en vacances',
    'Les écureuils ont des plans secrets',
    'Les tortues font du breakdance',
    'Les pastèques conspirent',
    'Les fourmis sont les nouvelles reines',
    'Les pommes de terre parlent',
    'Les girafes jouent à cache-cache',
    'Les croissants au beurre gouvernent',
    'Les épinards deviennent pop-stars',
    'Les nuages en colère',
    'Les chatons aux commandes',
    'Les éléphants font du patin à glace',
    'Les abeilles sont des ninjas',
    'Les crayons de couleur ont disparu !',
    'Les chaussettes à pois font la fête',
    'Les cornichons envahissent le frigo',
    'Les hippopotames dansent le tango',
    'Les hiboux ont des lunettes',
    'Les canards se prennent pour des détectives',
    'Les ballons de baudruche conspirent',
    'Les glaces fondent pour la liberté',
    'Les lamas sont des super-héros',
    'Les sardines font du yoga',
    'Les tapis volants en grève',
    'Les chouettes lisent des romans',
    "Les cacahuètes chantent l'opéra",
    'Les lapins font du skateboard',
    'Les marteaux parlent en secret',
    'Les dinosaures reviennent à la mode',
    "Les baguettes magiques s'égarent",
    'Les serpents jouent du violon',
    'Les étoiles filantes en panne',
    'Les pies volent des chaussettes',
    'Les tigres jouent aux échecs',
    'Les kiwis ont des ambitions politiques',
    'Les cocotiers font du hula-hoop',
    'Les hibiscus chantent du rock',
    'Les coccinelles font des marathons',
    'Les bananes préparent un complot',
    'Les marmottes cuisinent des crêpes',
    "Les chou-fleurs s'évadent",
    'Les coccinelles deviennent stars de cinéma',
    'Les chapeaux complotent en silence',
    'Les tapis prennent vie la nuit',
    "Les lampadaires rêvent d'aventure",
    'Les pianos dansent le twist',
    "Les parapluies s'envolent vers Mars",
    'Les miroirs révèlent des secrets',
    'Les téléphones chantent des berceuses',
    'Les biscuits marchent sur la lune',
    'Les horloges voyagent dans le temps',
    'Les scooters jouent au foot',
    'Les papillons apprennent le kung-fu',
    'Les carottes écrivent des poèmes',
    'Les nuages tricotent des écharpes',
    'Les horloges arrêtent le temps',
    'Les casseroles jouent de la batterie',
    'Les dictionnaires racontent des blagues',
    'Les fourchettes font des marathons',
    'Les bougies illuminent des histoires',
    'Les ombrelles deviennent détectives',
    'Les bouteilles en plastique chantent',
    'Les crayons dessinent des rêves',
    'Les cerfs-volants voyagent en secret',
    'Les tasses discutent entre elles',
    'Les oreillers racontent des histoires',
    'Les chaussons dansent la salsa',
    "Les lunettes voient l'invisible",
    "Les brosses à dents font de l'escrime",
    "Les fleurs s'échappent des vases",
    'Les rideaux murmurent des mystères',
    'Les arbres font des acrobaties',
    'Les crayons parlent en morse',
    'Les vélos explorent la jungle',
    'Les valises partent en croisière',
    'Les étoiles chantent des berceuses',
    'Les drapeaux dansent au vent',
    'Les guitares se rebellent',
    'Les montres racontent des histoires',
    'Les crayons de couleur jouent au cirque',
    'Les trompettes partent en randonnée',
    'Les casseroles inventent des recettes',
    'Les nuages jouent à cache-cache',
    'Les cerises organisent une fête',
    'Les balais nettoient l’espace',
    'Les ananas deviennent artistes',
    'Les avions en papier voyagent loin',
    'Les ampoules brillent de mille feux',
    'Les balançoires chantent au clair de lune',
    'Les pierres racontent des légendes',
    'Les citrons font de la magie',
    'Les sacs à dos gravissent des montagnes',
    'Les gants de cuisine orchestrent un opéra',
    'Les cactus dansent le flamenco',
    'Les coquillages murmurent des secrets',
    'Les horloges voyagent dans les rêves',
    'Les moineaux deviennent détectives',
    'Les grenouilles organisent des concerts',
    'Les tasses de thé voyagent dans le temps',
    'Les rubans dansent avec le vent',
    'Les parasols jouent au théâtre',
    'Les boutons partent à l’aventure',
    'Les bouquins discutent philosophie',
    "Les coussins s'envolent au paradis",
    'Les fantômes jouent aux échecs',
    'Les oiseaux font du tricot',
    'Les escaliers mènent au pays des rêves',
    'Les horloges tombent amoureuses',
    'Les bonnets s’organisent en syndicat',
    'Les lampes parlent aux ombres',
    'Les cerfs-volants disputent une course',
    'Les tasses préparent une révolution',
    'Les nuages peignent des tableaux',
    'Les tiroirs cachent des trésors',
    'Les horloges jouent du violon',
    'Les ours en peluche se transforment en ninjas',
    'Les savons dansent sous la douche',
    'Les coussins parlent de cinéma',
    'Les frigos racontent des blagues',
    'Les miroirs découvrent l’univers',
    'Les stylos inventent des langues',
    'Les ballons explorent les océans',
    'Les lampes s’éclairent d’idées',
    'Les claviers composent des symphonies',
    'Les poubelles deviennent stars de cinéma',
    'Les serviettes se préparent pour l’été',
    'Les rideaux jouent à cache-cache',
    'Les ventilateurs chantent l’opéra',
    'Les bouteilles en verre jouent aux pirates',
    'Les cerises écrivent des romans',
    'Les fourchettes se mettent au ballet',
    'Les assiettes planifient un voyage spatial',
    'Les ventilateurs voyagent dans le désert',
    'Les chapeaux de paille font la sieste',
    'Les crayons jouent au ping-pong',
    'Les horloges se déguisent en pirates',
    'Les nuages écrivent des poèmes',
    'Les brosses à cheveux deviennent magiciennes',
    'Les chaussures dansent le rock',
    'Les oreillers discutent philosophie',
    'Les lampes explorent la galaxie',
    'Les fourmis font du théâtre',
    'Les chaussons deviennent des héros',
    'Les parapluies jouent de la trompette',
    "Les livres s'évadent de la bibliothèque",
    'Les coussins préparent des cocktails',
    "Les vélos s'invitent au bal",
    'Les gants jouent du piano',
    "Les montres lisent l'avenir",
    'Les balais font des compétitions',
    "Les assiettes chantent l'opéra",
    'Les plantes rêvent de voyages',
    'Les lunettes deviennent détectives',
    "Les chaussettes s'envolent vers la lune",
    'Les miroirs racontent des secrets',
    'Les stylos dessinent des paysages',
    'Les couverts organisent un banquet',
    "Les fenêtres s'ouvrent sur l'inconnu",
    'Les tapis volants explorent le monde',
    'Les poules jouent au poker',
    'Les échelles atteignent les étoiles',
    'Les citrons préparent des cocktails',
    'Les pommes font du trampoline',
    'Les rideaux dansent avec le vent',
    'Les canapés racontent des histoires',
    'Les éléphants font du surf',
    'Les cactus jouent de la guitare',
    'Les lunettes de soleil voyagent dans le temps',
    'Les tapis jouent à cache-cache',
    'Les réfrigérateurs organisent des fêtes',
    'Les portefeuilles rêvent de trésors',
    "Les fusées en papier vont dans l'espace",
    'Les fraises font du vélo',
    'Les boîtes à musique enchantent les soirées',
    'Les armoires cachent des secrets',
    'Les tomates racontent des blagues',
    'Les casseroles préparent des symphonies',
    'Les avions en papier survolent des montagnes',
    'Les canards font du ski nautique',
    'Les lampadaires éclairent des mystères',
    'Les crayons de couleur organisent une fête',
    'Les poissons volants font des acrobaties',
    'Les paniers à pique-nique voyagent en forêt',
    'Les bancs de parc racontent des légendes',
    "Les tortues partent à l'aventure",
    'Les chauves-souris font du ballet',
    'Les cloches sonnent des mélodies',
    'Les horloges prennent des vacances',
    'Les feutres colorent le monde',
    'Les bottes explorent des cavernes',
    'Les grenouilles organisent des tournois',
    "Les feux d'artifice illuminent les rêves",
    'Les loutres font du patin à glace',
    'Les lamas font du saut en hauteur',
    'Les oranges deviennent peintres',
    'Les éléphants écrivent des romans',
    'Les coquillages chantent des berceuses',
    'Les sourires illuminent la nuit',
    'Les pommes de pin font des spectacles',
    'Les vélos font du roller',
    'Les parapluies dessinent des arcs-en-ciel',
    "Les plantes s'échappent des pots",
    'Les ballons de foot parlent stratégie',
    'Les tambours battent des records',
    'Les éponges racontent des aventures',
    'Les bâtons de pluie apaisent les tempêtes',
    "Les cerises font de l'alpinisme",
    'Les moulins à vent discutent météo',
    'Les poissons clowns animent des cirques',
    "Les ballons s'envolent pour des voyages",
    "Les toboggans glissent vers l'infini",
    'Les moustiques jouent de la trompette',
    'Les escargots montent des opéras',
    'Les étoiles filantes font des vœux',
    'Les cartes postales écrivent des romans',
    'Les hiboux enseignent la sagesse',
    'Les statues dansent au clair de lune',
    'Les bananes organisent des marathons',
    'Les noix de coco partent en croisière',
    'Les pigeons deviennent messagers',
    'Les ciseaux coupent des rubans magiques',
    'Les cerfs-volants volent au-dessus des océans',
    'Les fleurs parlent aux papillons',
    'Les noix chantent des chansons',
    'Les vagues surfent sur les rêves',
    'Les bonhommes de neige jouent au beach-volley',
    'Les étoiles de mer brillent sous la lune',
    'Les bougies éclairent des contes',
    'Les flocons dansent en hiver',
    'Les cannes à pêche pêchent des étoiles',
    'Les arcs-en-ciel colorent les cieux',
    'Les rivières murmurent des histoires',
    'Les feuilles dansent dans le vent',
    'Les pivoines parfument les rêves',
    'Les grenouilles chantent sous la pluie',
    'Les ruisseaux serpentent les montagnes',
    'Les coquilles Saint-Jacques explorent les fonds marins',
    'Les nuages flânent dans le ciel',
    'Les lucioles éclairent les sentiers',
    'Les pissenlits voyagent avec le vent',
    'Les tournesols suivent les étoiles',
    "Les libellules virevoltent sur l'eau",
    'Les bulles flottent vers le ciel',
    "Les bernard-l'hermite trouvent des trésors",
    "Les alouettes chantent l'aube",
    'Les loutres jouent avec les coquillages',
    'Les pins murmurent au vent',
    'Les collines roulent sous le ciel',
    'Les marguerites sourient au soleil',
    'Les ruisseaux murmurent des légendes',
    'Les papillons dansent avec les fleurs',
    'Les oies voyagent dans le ciel',
    'Les vergers murmurent des secrets',
    'Les mésanges sifflent des mélodies',
    'Les moissons dorent sous le soleil',
    'Les rossignols enchantent la nuit',
    'Les piverts tambourinent sur les arbres',
    'Les écureuils cachent des trésors',
    'Les mésanges bleues chantent aux étoiles',
    'Les renards explorent les prairies',
    'Les lapins bondissent de joie',
    'Les canetons suivent la rivière',
    'Les cygnes glissent sur le lac',
    'Les colibris butinent les fleurs',
    'Les rivières chantent la nature',
    'Les fleurs éclatent de couleurs',
    'Les jardins murmurent des histoires',
    'Les bosquets cachent des secrets',
    'Les collines ondulent sous le vent',
    "Les tourterelles roucoulent d'amour",
    'Les cèdres murmurent des contes',
    'Les lichens tapissent les rochers',
    "Les fougères dansent à l'ombre",
    'Les herbes folles chatouillent le ciel',
    'Les jonquilles annoncent le printemps',
    "Les nénuphars flottent sur l'eau",
    "Les pêcheries chantent à l'aube",
    'Les groseilles éclatent de saveur',
    "Les bambous s'inclinent avec grâce",
    'Les tulipes sourient au soleil',
    'Les myrtilles mûrissent sous la rosée',
    'Les acacias murmurent au vent',
    'Les ajoncs piquent de rire',
    'Les saules pleurent de joie',
    "Les colchiques annoncent l'automne",
    'Les mûriers offrent leurs fruits',
    'Les châtaigniers protègent les chemins',
    'Les ormes veillent sur la forêt',
    'Les marronniers éclatent de fleurs',
    'Les noisetiers cachent des trésors',
    "Les tilleuls parfument l'air",
    'Les cèpes jaillissent après la pluie',
    'Les fougères dansent sous les arbres',
    'Les chênes murmurent des légendes',
    'Les pivoines éclatent de couleurs',
    'Les jonquilles saluent le printemps'
];
