name : Main CI
run-name : ${{github.actor}} is running the main CI
on : 
  push : 
      branches : [main]
  pull_request : 
      branches : [main]
jobs:
  run-backend : 
    runs-on : ubuntu-latest

    strategy : 
      matrix : 
        node-version : ["18.x"]

    steps : 
      - uses : actions/setup-node@v3
        with :
          node-version : "18.x"
      - uses : action/checkout@v3
      - run : npm install
        working-directory : ./back
      - run : npm run start
        working-directory : ./back