name : Main CI

run-name : ${{github.actor}} is running the main CI

on : 
  push : 
      branches : [main]
  pull_request : 
      branches : [main]


jobs:
  build-backend : 
    runs-on : ubuntu-latest

    strategy : 
      matrix : 
        node-version : ["18.20.2"]

    steps : 
      - uses : actions/checkout@v4
      - uses : actions/setup-node@v4
        with : 
          node-version : "18.20.2"
      - run : npm install
        working-directory : ./back
      - run: npm run build --if-present
        working-directory : ./back