name : Main CI

run-name : ${{github.actor}} is running the main CI

on : 
  push : 
      branches : [main, front, back, CI]
  pull_request : 
      branches : [main]


jobs:
  build-backend : 
    runs-on : ubuntu-latest

    strategy : 
      matrix : 
        node-version : ["18.x"]

    steps : 
      - uses : actions/checkout@v4
      - uses : actions/setup-node@v4
        with : 
          node-version : "18.x"
      - run : npm run build-render
        working-directory : ./back

  build-frontend : 
    runs-on : ubuntu-latest

    strategy : 
      matrix : 
        node-version : ["18.x"]

    steps : 
      - uses : actions/checkout@v4
      - uses : actions/setup-node@v4
        with : 
          node-version : "18.x"
      - run : npm install
        working-directory : ./client
      - run : npm run build
        working-directory : ./client
